<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.marginallyclever</groupId>
    <artifactId>WeavingRadon</artifactId>
    <version>1.1</version>
    <description>Weaving thread on a loom to approximate an image.</description>


    <issueManagement>
        <url>https://github.com/MarginallyClever/weaving_algorithm/issues</url>
        <system>GitHub Issues</system>
    </issueManagement>

    <licenses>
        <license>
            <name>GPLv2</name>
            <url>https://opensource.org/licenses/GPL-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/MarginallyClever/weaving_algorithm</url>
        <connection>scm:git:git@github.com:MarginallyClever/Makelangelo-software.git</connection>
    </scm>

    <organization>
        <name>Marginally Clever Robots, Limited.</name>
        <url>https://www.marginallyclever.com/</url>
    </organization>

    <developers>
        <developer>
            <id>i-make-robots</id>
            <name>Dan Royer</name>
            <email>dan@marginallyclever.com</email>
            <url>https://github.com/i-make-robots</url>
            <roles>
                <role>architect</role>
                <role>developer</role>
            </roles>
            <timezone>-8</timezone>
        </developer>
    </developers>

    <properties>
        <minimum.java.version>21</minimum.java.version>
        <maven.compiler.source>${minimum.java.version}</maven.compiler.source>
        <maven.compiler.target>${minimum.java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <!-- Compiler Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${minimum.java.version}</source>
                    <target>${minimum.java.version}</target>
                    <release>${minimum.java.version}</release>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!-- JAR Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <mainClass>com.marginallyclever.weavingradon.WeavingApp</mainClass>
                            <addClasspath>true</addClasspath>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <!-- Assembly Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.marginallyclever.weavingradon.WeavingApp</mainClass>
                            <addClasspath>true</addClasspath>
                        </manifest>
                        <manifestEntries>
                            <Implementation-Version>${project.version}</Implementation-Version>
                        </manifestEntries>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <pluginRepositories>
        <pluginRepository>
            <id>maven2</id>
            <url>https://repo.maven.apache.org/maven2/</url>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>maven_central</id>
            <name>Maven Central</name>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- dockable windows -->
        <dependency>
            <groupId>io.github.andrewauclair</groupId>
            <artifactId>modern-docking-api</artifactId>
            <version>0.11.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.andrewauclair</groupId>
            <artifactId>modern-docking-single-app</artifactId>
            <version>0.11.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.andrewauclair</groupId>
            <artifactId>modern-docking-ui</artifactId>
            <version>0.11.1</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>3.2.5</version>
        </dependency>
        <dependency>
            <groupId>com.github.weisj</groupId>
            <artifactId>jsvg</artifactId>
            <version>1.3.0</version>
        </dependency>

        <!-- qoi image format support -->
        <dependency>
            <groupId>me.saharnooby</groupId>
            <artifactId>qoi-java</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>me.saharnooby</groupId>
            <artifactId>qoi-java-awt</artifactId>
            <version>1.2.1</version>
        </dependency>
        <!-- webp image format support -->
        <dependency>
            <groupId>org.sejda.imageio</groupId>
            <artifactId>webp-imageio</artifactId>
            <version>0.1.6</version>
        </dependency>
        <!-- vector stuff -->
        <dependency>
            <groupId>javax.vecmath</groupId>
            <artifactId>vecmath</artifactId>
            <version>1.5.2</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>